### ISSUE TITLE
.,

### ISSUE THREAD

**Issue by talneyadi** [vlad1193/will_you_find_this#1]
Rainer,
Why would you delete it? I'm not gonna have anything at all, not you, not your love, nothing. So why would you take the only thing I could get. Just text files that apparently mean nothing to you. Why are you being such an asshole?

The things I said, it really meant nothing. And I told you that I didn't mean it. But you decided to go ahead and believe whatever suits you.

I'm not exactly sure what you mean by "No matter what decision you make with that - i think life will happen the way it should" if by that you’re implying that I might go and use whatever I have against you, then I really hate you and I hate everything you are. If I wanted to hurt you I could've done that a long time ago. I have your wife’s number, her social media accounts thanks to her amazing stalking skills and I know where you live. But I'm not that person you think I am. I just wanted something to remember you by since I lost everything.

But thank you - for showing me how you really see me and what I mean to you.

I'm currently deleting everything I have. You don't have to worry about this anymore.

**Comment by vlad1193** [comment]
I can be an asshole. 

Let me restore the repo...

**Comment by talneyadi** [comment]
Why are you doing this? Are you trying to get even because of what I said yesterday? 

Now that I've deleted all the photos, screenshots and conversations
